### ISSUE TITLE
[Intermittent] 404 when loading the composer

### ISSUE THREAD

**Issue by dilinisg** [ballerina-lang/composer#3195]
Release 0.93

404 is observed when trying to open the composer

![404](https://user-images.githubusercontent.com/1845370/30919758-f81fe06a-a3bf-11e7-9c33-b26baac685d6.png)

**Comment by manjulaRathnayaka** [comment]
This happens because load balancer is not updated for newly created ballerina composer URLs. It takes 10seconds to appear. I am working on a fix to identify this and reload the page as a quick fix from load balancer level. To properly fix this usability issue, we have to increase the frequency of load balancer configuration updates.
