### ISSUE TITLE
Resource config: second http method is not added correctly from design view

### ISSUE THREAD

**Issue by erandidesilva** [ballerina-lang/composer#4025]
Browser: Chrome Version 62.0.3202.62 (Official Build) (64-bit)

As shown in the below image, when adding the second http method it's added without the double quotes.

![com_0 94_trans_8](https://user-images.githubusercontent.com/15624590/31773036-1c38f8ba-b4ff-11e7-8288-6e16e596448a.png)

**Comment by hevayo** [comment]
Hi 
Here the user is capable of providing a variable identifier instead of a string. So increase of providing a string user has to explicitly type the enclosing quotes. 

will reduce the severity of this issue due to above and will keep this open till we find a solution for the usability issue.

Thanks
Jo
